/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package everafterjourney;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Cruz
 */
public class GuestHome extends javax.swing.JFrame {

    /**
     * Creates new form GuestHome
     */
    public GuestHome() {
        initComponents();
        
        String guestname = GuestHome.getGuestName();
        jLabel3.setText("Hello, " + guestname + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private static String guestNameFromSelect;

    public static void setGuestName(String guestname) {
        guestNameFromSelect = guestname;
    }

    public static String getGuestName() {
        return guestNameFromSelect;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        jLabel3.setText("Hello, ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 412, -1));

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jLabel1.setText("You are invited to the most wonderful wedding of the year!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 609, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 131, 74)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel4.setText("Seat Arrangement");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 30));

        jButton1.setBackground(new java.awt.Color(169, 131, 74));
        jButton1.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(228, 233, 229));
        jButton1.setText("Check your seat ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 111, 300, 185));

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        jLabel5.setText("You can see your seat and Invitation here");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 337, 315));

        jButton4.setBackground(new java.awt.Color(169, 131, 74));
        jButton4.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 81, 36));

        jPanel1.setBackground(new java.awt.Color(169, 131, 74));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 490));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/791x563.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 710, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String SUrl = "jdbc:mysql://localhost:3306/everafterjourney_database";
            String SUser = "root";
            String SPass = "";

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();   

            String GuestName = GuestHome.getGuestName();
            System.out.println("Guest Name: " + GuestName);

            FirstTheme.setGuestName(GuestName);
            SecondTheme.setGuestName(GuestName);
            ThirdTheme.setGuestName(GuestName);

            String sql = "SELECT signup_id FROM guests WHERE guestname = '" + GuestName + "'";

            ResultSet rs = st.executeQuery(sql);

            int signUpID = -1;
            if (rs.next()) {
                signUpID = rs.getInt("signup_id");
                System.out.println("Sign Up ID: " + signUpID);

                View_ThirtySeats.setMyID(signUpID);
                View_FiftySeats.setMyID(signUpID);
                View_SeventyFiveSeats.setMyID(signUpID);
                View_OneHundredSeats.setMyID(signUpID);
            }

            rs.close();

            String sql2 = "SELECT capacity FROM signup WHERE id = " + signUpID;
            ResultSet rs2 = st.executeQuery(sql2);

            String capacity = "";
            if (rs2.next()) {
                capacity = rs2.getString("capacity");
                System.out.println("Capacity: " + capacity);
            }

            rs2.close(); 
            st.close(); 
            con.close(); 

            switch (capacity) {
                case "15-30":
                    View_ThirtySeats viewThirty = new View_ThirtySeats();
                    viewThirty.setVisible(true);
                    break;
                case "31-50":
                    View_FiftySeats viewFifty = new View_FiftySeats();
                    viewFifty.setVisible(true);
                    break;
                case "51-75":
                    View_SeventyFiveSeats viewSeventyFive = new View_SeventyFiveSeats();
                    viewSeventyFive.setVisible(true);
                    break;
                case "76-100":
                    View_OneHundredSeats viewOneHundred = new View_OneHundredSeats();
                    viewOneHundred.setVisible(true);
                    break;
                default:
                    System.out.println("Unknown capacity: " + capacity);
                    break;
            }

            this.setVisible(false);

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Start start = new Start();
        start.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
